runtime: php72

runtime_config:
  document_root: .

entrypoint: 
  serve index.php

env_variables:

CLOUDSQL_USER: document_root
CLOUDSQL_DB: database
CLOUDSQL_PASSWORD: SS$$1254
CLOUD_DSN: /cloudsql/capable-passage-339910
